version: "3.9"

services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app
      - /app/node_modules
    depends_on:
      - frontend

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Vite dev server
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # nếu Vite hot reload không hoạt động trong Docker
